#!/bin/bash
# Stop and Flush All Iptables Rules, since some Linux distros like Debian do not have /etc/init.d/iptables stop script 
# Based on:
https://bash.cyberciti.biz/security/shell-script-to-stop-linux-firewall/

sudo iptables -F
sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t mangle -F
sudo iptables -t mangle -X
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
